MCU = RP2040
BOOTLOADER = rp2040

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
I2C_DRIVER = vendor

ENCODER_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor